---
name: Colin F. Doms
position: "Data Scientist"
address: "USA"
email: "colindoms@gmail.com"
profilepic: "cfd13.jpeg"
twitter: colindoms
github: cdoms
linkedin: cdoms
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Colin is a data scientist with experience in B2B settings and a background in causal inference from training in the social sciences."
output: vitae::twentyseconds
---
```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tinytex)
library(vitae)
library(tidyverse)
library(tibble)
options(tinytex.verbose = TRUE)
```

```{r, echo = FALSE, include = FALSE, warning = FALSE, message=FALSE}
entry <- function(title, organization, place, duration){
  tribble(
    ~name, ~event, ~location,  ~year,
    title, organization, place, duration) %>%
    detailed_entries(what = name,
                     with = event,
                     where = location,
                     when = year)
}

```

# Some stuff about me

 * I have a master's from Columbia University.
 * I was recently published in *Scientific Reports*.
 * I started an S-Corp while freelancing and am looking to use my technical skills in a new position with what I learned about business in a team environment.
 
# Experience
```{r experience}
entry("Lead Adjunct Associate Faculty", "New York, NY", "Columbia University", "Present")

entry(
  "Data Scientist", "New York, NY", "IBM", "2015-2017")


```

 
# Education
```{r education}
entry(
  "M.A., Quantitative Methods in the Social Sciences", "New York, NY", "Columbia University", "2015")

```

